logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.com.zaxxer.hikari=WARN


api.treasury.base-url=https://api.fiscaldata.treasury.gov/services/api/fiscal_service/
management.endpoints.web.exposure.include=health,info,prometheus

